apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQ=  # password
  ADMIN_PASSWORD: YWRtaW5wYXNz
  MANU1_PASSWORD: bWFudXBhc3Mx
  MANU2_PASSWORD: bWFudXBhc3My